name: Backend Tests

on:
  push:
    branches: [ main, develop ]
    paths: 
      - 'backend/**'
      - '.github/workflows/backend-tests.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-tests.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
        
    - name: Verify uv installation
      run: uv --version
      
    - name: Install dependencies
      working-directory: ./backend
      run: |
        uv sync --dev
        
    - name: Run tests with coverage
      working-directory: ./backend
      run: |
        uv run pytest --cov=. --cov-report=xml --cov-report=term-missing --disable-warnings
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      if: success()
      with:
        file: ./backend/coverage.xml
        directory: ./backend
        flags: backend
        name: backend-coverage
        fail_ci_if_error: false
        
    - name: Coverage Summary
      working-directory: ./backend
      run: |
        echo "## Test Coverage Report" >> $GITHUB_STEP_SUMMARY
        uv run pytest --cov=. --cov-report=term-missing --tb=no -q >> $GITHUB_STEP_SUMMARY || true
